'Application settings'

MAX_SEQUENCE_LENGTH = 4

# Times below are in seconds

DISCARD_PRESSES_OLDER_THAN = 1
MIN_WAIT = 1.5
MAX_WAIT = 5
MAX_REACTION = 2.5
MIN_REACTION = .060
WAIT_RANGE = MAX_WAIT - MIN_WAIT
WIN_BLINK_TIME = .3
WIN_BLINKS = 1
